### ISSUE TITLE
encoded outputs

### ISSUE THREAD

**Issue by themighty1** [chart21/CRGC#3]
In this scheme final output wires are not flipped. What if the generator applied an OTP to the output wires? Then his OTP would be the decoding table and the evaluator's output of the circuit would be encoded output.
Or is there a reason that if OTP is applied to the output wires than the scheme would break?

**Comment by chart21** [comment]
Final output wires do not get flipped so that the evaluator can obtain the correct output of the circuit without interaction. 

You can use an OTP at the end or flip final output wires. That is no problem. However, since the decoding table is fixed it only gives you security for a single evaluation (or batch of evaluation).

What you could do is, let the Evaluator get 1000 outputs with AES and OTP. Then give the Evaluator the decoding table. 

However, once you give it the decoding table once it can now evaluate the circuit without interaction and use the obtained decoding table to obtain the output.
