### ISSUE TITLE
Understanding the scheme

### ISSUE THREAD

**Issue by themighty1** [chart21/CRGC#5]
I was trying to wrap my mind around how the scheme works by making this diagram. The first wires which go into the XOR gates are G's and E's input wires. The yellow wires are the flipped wires.

![diagram](https://user-images.githubusercontent.com/555272/160276339-ef9025d3-85f6-481f-8154-8f0ad2bd37d6.png)

My thought process is as follows:

- G sees that wires 1 and 2 are flipped, so he assign this truth table to the XOR gate: 0110 (acc.to Figure 1 (d) of the paper)

- G sees that only the left parent to the AND gate is flipped, which corresponds to this truth table: 0100. But since wire 3 is flipped, that table must be flipped to 1011. This is what he assigns to the AND gate.

- When E sees that XOR's truth table is 0110, it means only one of the two options:
A) both wires 1 and 2 were flipped or
B) neither wire 1 nor wire 2 were flipped

- But when E sees the AND's truth table, there is only one possibility to interpret it: left parent was flipped and output was flipped.

- Since he learns that wire 2 was flipped, that leaves him only option A) and thus he learns that wire 1 was flipped.

I'm sure it cannot be broken that easily. Please help me see what I'm missing.
Thanks.

**Comment by chart21** [comment]
Hi, I think it's a great example to illustrate the trade-offs and capabilities of this scheme. As in the paper, we assume that the evaluator knows every gate in the circuit. 

A gate can provide indistinguishability obfuscation if:
1. It is on level 1 of the circuit
2. It is a balanced gate
3. It is a potentially fixed gate
4. It is a potentially intermediary gate


Option 1 and 2 are clearly not met for the AND gate. 

Let's explore Option 2:

Using algorithm 4 from the paper, we can see that a potentially fixed imbalanced gate is present if the left or the right parent of the gate are potentially fixed. The example you drew is the only constellation where this is not the case.

Let's assume we had the following situation.

```
L1          L2

XOR
          AND (g)
AND  
```

In this case, the right parent is potentially fixed, so g is also potentially fixed. We can easily see that the probability of g being fixed is 50%. Thus, we can use equation 13 from the paper to set the probability of replacing g with NOR (in case it is fixed) to 100%. Now the evaluator cannot infer whether g is an obfuscated NOR gate or still the plain AND gate. Thus we achieved indistinguishability obfuscation.

Again, the AND gate is potentially fixed in all other constellations (parents: XOR, AND / AND, AND / AND XOR).

In your example, we cannot utilize this observation.

Let's explore Option 4:

Only the whole circuit can show if the AND gate is a potentially intermediary gate. Let's assume the following example:

```
L1          L2         L3 

XOR
          AND (g)
AND  
                      AND ...
XOR
          AND
AND
```


In this simple example, each path from g to a final output gate contains a potentially fixed gate. In case g is an intermediary gate, it can be modified arbitrarily without hurting the integrity of the scheme. We can again obtain the right probability q to achieve indistinguishability obfuscation.

The library has the functionality to identify all potentially intermediary gates.


Of course, there is the possibility that all 4 options are not satisfied for g. In this case, we would assign g to the non-reusable section of a PRGC. If we use a CRGC, we risk input leakge. In our paper we called gates such as g potentially revealing gates.
Potentially revealing gates leak their input wire bits with certainty. However, this does not mean they also leak an input bit of the generator with certainty.

Let's assume the following example:


```
L1    L2      L3

XOR
      XOR    
XOR  
             AND (g) ...
XOR
      XOR
XOR
```


Clearly, g is not a fixed gate in this example. Let's also assume it is not a potentially intermediary gate. In this case, it is a potentially revealing gate. Let's inspect the truth table (e.g. 0100). We can easily revert bit flipping as the unique case can only come from parent inputs of 1,1. We just revealed the output wires of the gates on L2 with certainty. However, the gates on L1 again recover obfuscation. Below, you can see what exactly can be inferred from the potentially revealing gate. Observe that no input of g is revealed with certainty.


        
```
                    L1              L2          L3
g = 0/1        XOR -> 0/1
                                XOR -> 1   
g = 1/0        XOR -> 1/0 
                                            AND (g) -> 1
g = 0/1        XOR -> 0/1
                                XOR -> 1
g = 1/0        XOR -> 1/0
```
            

This is described by the paper in the section on potentially revealing gate: "Observe that a potentially revealing gate gpr only reveals an input bit ai of the generator if there is at most one balanced gate on the path of gpr to a0"


The leakage prediction of this library checks exactly this condition. Only when there are less than two balanced gates in the path to a generator input, we describe the generator input as leaked.


So let's resume:

1. If options 1-4 are not met, g is a potentially revealing gate
2. If there are less than two balanced gates between a potentially revealing gate and a generator input, the generator input is leaked with certainty.

Thus, in your example, the generator inputs will indeed be leaked with certainty if g is not a potentially intermediary gate.    
Note that the library will detect this. However, in the circuits tested, only 1-2 input bits were leaked in the circuits. For instance, the least significant bit of an addition is just XOR(lsb(g),lsb(e)) and thus reveals this generator input bit with certainty.
Thus, either the tested cirucits did not have this XOR,XOR,AND constellation on L1, or at least the AND gate was a potentially intermediary gate.  

Note that when using CRGCs, we have the quite complex case in that we reveal partial knowledge of the circuit with each potentially revealing gate. Also, further knowledge on other gates may be inferred if one input bit is leaked with certainty. Thus, we do not claim an upper bound on input leakage and cannot exclude that there is more sophisticated analysis that can infer more. Thus, for provable input privacy PRGCs should be used.

**Comment by themighty1** [comment]
Thank you. That was very informative. It answered a lot of questions.

On further thought, what are your thoughts about avoiding the potentially
revealing XOR/XOR/AND constellation on Levels > 1 in this way:

- G sets an arbitrary wire to 1
- when he encounters the pot.rev. XOR/XOR/AND, he inserts a new dummy AND gate which returns the XOR gate's wire

![diag2](https://user-images.githubusercontent.com/555272/160287312-02e33efa-6dc6-4272-84cc-60fec9a2d364.png)

Would that make any difference?

**Comment by chart21** [comment]
It would certainly trick the leakage prediction algorithm. But only because it does not have any prior knowledge on the generator inputs.

However, if we still assume in the threat model that the evaluator knows every gate in the original circuit then it can detect the dummy gates and reconstruct the original circuit given the prior knowledge that a generator's dummy gate wire is always 1.
 
Adding dummy gates is only promising if the evaluator does not know the original circuit's construction. 

Adding artificial gates where the generator input is not fixed but can be 0 or 1 will certainly provide obfuscation. However, this will break the integrity of the circuit. Thus you need to recover the circuit's integrity at some point in a deeper level.

Your approach can be successful if you achieve the following:
1. add an artificial gate with an unfixed generator input
2. recover the circuit's integrity without revealing the obfuscation from step 1

This might be hard or even impossible to achieve. But you can give it a try.
